//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharesBrokerASPClient {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm loginForm;
		
		protected System.Web.UI.WebControls.TextBox loginUsername;
		
		protected System.Web.UI.WebControls.TextBox loginPassword;
		
		protected System.Web.UI.WebControls.Button loginButton;
		
		protected System.Web.UI.HtmlControls.HtmlForm registerForm;
		
		protected System.Web.UI.WebControls.TextBox regUsername;
		
		protected System.Web.UI.WebControls.TextBox regPassword;
		
		protected System.Web.UI.WebControls.TextBox regConPassword;
		
		protected System.Web.UI.WebControls.Button registerButton;
		
		protected System.Web.UI.WebControls.Label notifcationLabel;
	}
}
